Refactoring parser: from recursive-descent LL(1)-parser *with* backtracking to recursive-descent LL(2)-parser *without* backtracking
Removing backtracking introduces 2-token lookahead in order to
deterministically parse Python's grammar. Overall, the code seems much more
straightforward to read and understand after the conversion.

Also, error messages have improved. The backtracking engine would only allow
full matches and match non-greedily. Consider the grammar

    if_stmt: 'if' test ':' suite ('elif' test ':' suite)* ['else' ':' suite]

and the following input program:

    if num % 2 == 0:
        True orr False

Since there is a syntax error in ``suite``, the backtracking engine would
only parse up to the last valid token and emit an error as follows:

    if num % 2 == 0:
                   ^
    SyntaxError: invalid syntax

Now, the parser emits the following more precise error:

    True orr False
           ^
    SyntaxError: invalid syntax